# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1622, 818)
        MainWindow.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:0, stop:0.8125 rgba(8, 0, 127, 254), stop:0.988764 rgba(34, 135, 229, 255));\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_73 = QtWidgets.QLabel(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(460, 0, 641, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setIndent(4)
        self.label_73.setObjectName("label_73")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 0, 791, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../AAAAAA/UI_tracker/images_test/frame3.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stopBn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBn.setGeometry(QtCore.QRect(180, 130, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.stopBn.setFont(font)
        self.stopBn.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 137, 191);\n"
"}")
        self.stopBn.setObjectName("stopBn")
        self.closeLightBn = QtWidgets.QPushButton(self.centralwidget)
        self.closeLightBn.setGeometry(QtCore.QRect(180, 190, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.closeLightBn.setFont(font)
        self.closeLightBn.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 137, 191);\n"
"}")
        self.closeLightBn.setObjectName("closeLightBn")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 90, 291, 171))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../AAAAAA/UI_tracker/images_test/frame.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.startBn = QtWidgets.QPushButton(self.centralwidget)
        self.startBn.setGeometry(QtCore.QRect(30, 130, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.startBn.setFont(font)
        self.startBn.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 137, 191);\n"
"}")
        self.startBn.setObjectName("startBn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 90, 211, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_4.setMidLineWidth(0)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../AAAAAA/UI_tracker/images_test/frame3.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_74 = QtWidgets.QLabel(self.centralwidget)
        self.label_74.setGeometry(QtCore.QRect(70, 90, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setIndent(4)
        self.label_74.setObjectName("label_74")
        self.openLightBn = QtWidgets.QPushButton(self.centralwidget)
        self.openLightBn.setGeometry(QtCore.QRect(30, 190, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.openLightBn.setFont(font)
        self.openLightBn.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 137, 191);\n"
"}")
        self.openLightBn.setObjectName("openLightBn")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 291, 491))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(0, 0, 127);")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../AAAAAA/UI_tracker/images_test/frame.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 260, 211, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_5.setMidLineWidth(0)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../AAAAAA/UI_tracker/images_test/frame3.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.clearBn = QtWidgets.QPushButton(self.centralwidget)
        self.clearBn.setGeometry(QtCore.QRect(240, 300, 41, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.clearBn.setFont(font)
        self.clearBn.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 137, 191);\n"
"}")
        self.clearBn.setObjectName("clearBn")
        self.label_75 = QtWidgets.QLabel(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(80, 260, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setIndent(4)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(50, 310, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_76.setFont(font)
        self.label_76.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setIndent(4)
        self.label_76.setObjectName("label_76")
        self.arm_joint1 = QtWidgets.QTextEdit(self.centralwidget)
        self.arm_joint1.setGeometry(QtCore.QRect(120, 310, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.arm_joint1.setFont(font)
        self.arm_joint1.setStyleSheet("border: 1px solid rgb(66, 104, 228);   /* 边框 */  \n"
"alternate-background-color: rgb(255, 255, 255);\n"
"border-radius: 3px;   /* 圆角 */\n"
"background-color: rgba(0, 170, 255, 100);\n"
"color: rgb(0, 255, 255);\n"
"")
        self.arm_joint1.setObjectName("arm_joint1")
        self.label_77 = QtWidgets.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(50, 350, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setIndent(4)
        self.label_77.setObjectName("label_77")
        self.arm_joint2 = QtWidgets.QTextEdit(self.centralwidget)
        self.arm_joint2.setGeometry(QtCore.QRect(120, 350, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.arm_joint2.setFont(font)
        self.arm_joint2.setStyleSheet("border: 1px solid rgb(66, 104, 228);   /* 边框 */  \n"
"alternate-background-color: rgb(255, 255, 255);\n"
"border-radius: 3px;   /* 圆角 */\n"
"background-color: rgba(0, 170, 255, 100);\n"
"color: rgb(0, 255, 255);\n"
"")
        self.arm_joint2.setObjectName("arm_joint2")
        self.label_78 = QtWidgets.QLabel(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(50, 390, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setIndent(4)
        self.label_78.setObjectName("label_78")
        self.arm_joint3 = QtWidgets.QTextEdit(self.centralwidget)
        self.arm_joint3.setGeometry(QtCore.QRect(120, 390, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.arm_joint3.setFont(font)
        self.arm_joint3.setStyleSheet("border: 1px solid rgb(66, 104, 228);   /* 边框 */  \n"
"alternate-background-color: rgb(255, 255, 255);\n"
"border-radius: 3px;   /* 圆角 */\n"
"background-color: rgba(0, 170, 255, 100);\n"
"color: rgb(0, 255, 255);\n"
"")
        self.arm_joint3.setObjectName("arm_joint3")
        self.label_79 = QtWidgets.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(60, 430, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_79.setFont(font)
        self.label_79.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setIndent(4)
        self.label_79.setObjectName("label_79")
        self.arm_high = QtWidgets.QTextEdit(self.centralwidget)
        self.arm_high.setGeometry(QtCore.QRect(120, 430, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.arm_high.setFont(font)
        self.arm_high.setStyleSheet("border: 1px solid rgb(66, 104, 228);   /* 边框 */  \n"
"alternate-background-color: rgb(255, 255, 255);\n"
"border-radius: 3px;   /* 圆角 */\n"
"background-color: rgba(0, 170, 255, 100);\n"
"color: rgb(0, 255, 255);\n"
"")
        self.arm_high.setObjectName("arm_high")
        self.sendBn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBn.setGeometry(QtCore.QRect(240, 390, 41, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.sendBn.setFont(font)
        self.sendBn.setStyleSheet("QPushButton{\n"
"background-color: rgb(65, 137, 191);\n"
"}")
        self.sendBn.setObjectName("sendBn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 470, 291, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_6.setMidLineWidth(0)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../AAAAAA/UI_tracker/images_test/frame3.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_84 = QtWidgets.QLabel(self.centralwidget)
        self.label_84.setGeometry(QtCore.QRect(80, 470, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_84.setFont(font)
        self.label_84.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setIndent(4)
        self.label_84.setObjectName("label_84")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1300, 110, 211, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_12.setMidLineWidth(0)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../AAAAAA/UI_tracker/images_test/frame3.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_87 = QtWidgets.QLabel(self.centralwidget)
        self.label_87.setGeometry(QtCore.QRect(1280, 100, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_87.setFont(font)
        self.label_87.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_87.setText("")
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setIndent(4)
        self.label_87.setObjectName("label_87")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1240, 100, 341, 641))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../AAAAAA/UI_tracker/images_test/frame.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_88 = QtWidgets.QLabel(self.centralwidget)
        self.label_88.setGeometry(QtCore.QRect(1340, 110, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_88.setFont(font)
        self.label_88.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setIndent(4)
        self.label_88.setObjectName("label_88")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(1260, 590, 301, 131))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: rgba(0, 170, 255, 100);")
        self.label_27.setText("")
        self.label_27.setTextFormat(QtCore.Qt.AutoText)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setIndent(10)
        self.label_27.setObjectName("label_27")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 100, 851, 641))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../AAAAAA/UI_tracker/images_test/frame.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setIndent(10)
        self.label_2.setObjectName("label_2")
        self.label_display = QtWidgets.QLabel(self.centralwidget)
        self.label_display.setEnabled(True)
        self.label_display.setGeometry(QtCore.QRect(360, 110, 831, 621))
        self.label_display.setMinimumSize(QtCore.QSize(750, 454))
        self.label_display.setMaximumSize(QtCore.QSize(1152, 648))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_display.setFont(font)
        self.label_display.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_display.setAutoFillBackground(False)
        self.label_display.setStyleSheet("")
        self.label_display.setText("")
        self.label_display.setPixmap(QtGui.QPixmap("../AAAAAA/UI_tracker/images_test/0104a.jpg"))
        self.label_display.setScaledContents(True)
        self.label_display.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display.setObjectName("label_display")
        self.label_89 = QtWidgets.QLabel(self.centralwidget)
        self.label_89.setGeometry(QtCore.QRect(1270, 660, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_89.setFont(font)
        self.label_89.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setIndent(4)
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.centralwidget)
        self.label_90.setGeometry(QtCore.QRect(1260, 590, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_90.setFont(font)
        self.label_90.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setIndent(4)
        self.label_90.setObjectName("label_90")
        self.length = QtWidgets.QLabel(self.centralwidget)
        self.length.setGeometry(QtCore.QRect(1410, 600, 131, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.length.setFont(font)
        self.length.setStyleSheet("background-color:rgb(78, 157, 236);")
        self.length.setText("")
        self.length.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.length.setObjectName("length")
        self.label_81 = QtWidgets.QLabel(self.centralwidget)
        self.label_81.setGeometry(QtCore.QRect(30, 600, 88, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_81.setFont(font)
        self.label_81.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setIndent(4)
        self.label_81.setObjectName("label_81")
        self.label_85 = QtWidgets.QLabel(self.centralwidget)
        self.label_85.setGeometry(QtCore.QRect(40, 710, 55, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_85.setFont(font)
        self.label_85.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setIndent(4)
        self.label_85.setObjectName("label_85")
        self.speedLb = QtWidgets.QLabel(self.centralwidget)
        self.speedLb.setGeometry(QtCore.QRect(160, 550, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.speedLb.setFont(font)
        self.speedLb.setStyleSheet("background-color:rgb(78, 157, 236)")
        self.speedLb.setText("")
        self.speedLb.setObjectName("speedLb")
        self.label_86 = QtWidgets.QLabel(self.centralwidget)
        self.label_86.setGeometry(QtCore.QRect(40, 670, 55, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_86.setFont(font)
        self.label_86.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setIndent(4)
        self.label_86.setObjectName("label_86")
        self.label_83 = QtWidgets.QLabel(self.centralwidget)
        self.label_83.setGeometry(QtCore.QRect(40, 640, 55, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_83.setFont(font)
        self.label_83.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setIndent(4)
        self.label_83.setObjectName("label_83")
        self.label_82 = QtWidgets.QLabel(self.centralwidget)
        self.label_82.setGeometry(QtCore.QRect(30, 520, 88, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_82.setFont(font)
        self.label_82.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setIndent(4)
        self.label_82.setObjectName("label_82")
        self.joint3_Lb = QtWidgets.QLabel(self.centralwidget)
        self.joint3_Lb.setGeometry(QtCore.QRect(160, 710, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.joint3_Lb.setFont(font)
        self.joint3_Lb.setStyleSheet("background-color:rgb(78, 157, 236)")
        self.joint3_Lb.setText("")
        self.joint3_Lb.setObjectName("joint3_Lb")
        self.label_80 = QtWidgets.QLabel(self.centralwidget)
        self.label_80.setGeometry(QtCore.QRect(30, 550, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setIndent(4)
        self.label_80.setObjectName("label_80")
        self.distanceLb = QtWidgets.QLabel(self.centralwidget)
        self.distanceLb.setGeometry(QtCore.QRect(160, 590, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.distanceLb.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.distanceLb.setFont(font)
        self.distanceLb.setStyleSheet("background-color:rgb(78, 157, 236)")
        self.distanceLb.setText("")
        self.distanceLb.setObjectName("distanceLb")
        self.joint2_Lb = QtWidgets.QLabel(self.centralwidget)
        self.joint2_Lb.setGeometry(QtCore.QRect(160, 670, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.joint2_Lb.setFont(font)
        self.joint2_Lb.setStyleSheet("background-color:rgb(78, 157, 236);\n"
"border-color: rgb(85, 0, 255);")
        self.joint2_Lb.setText("")
        self.joint2_Lb.setObjectName("joint2_Lb")
        self.joint1_Lb = QtWidgets.QLabel(self.centralwidget)
        self.joint1_Lb.setGeometry(QtCore.QRect(160, 630, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 157, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.joint1_Lb.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.joint1_Lb.setFont(font)
        self.joint1_Lb.setStyleSheet("background-color:rgb(78, 157, 236)")
        self.joint1_Lb.setText("")
        self.joint1_Lb.setObjectName("joint1_Lb")
        self.directionLb = QtWidgets.QLabel(self.centralwidget)
        self.directionLb.setGeometry(QtCore.QRect(160, 510, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.directionLb.setFont(font)
        self.directionLb.setStyleSheet("background-color:rgb(78, 157, 236)")
        self.directionLb.setText("")
        self.directionLb.setObjectName("directionLb")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(1370, 170, 181, 31))
        self.comboBox.setStyleSheet("background-color: rgba(0, 170, 255, 100);\n"
"border-color: rgba(0, 170, 255, 100);")
        self.comboBox.setObjectName("comboBox")
        self.statistic_label = QtWidgets.QLabel(self.centralwidget)
        self.statistic_label.setGeometry(QtCore.QRect(10, 770, 1551, 29))
        self.statistic_label.setMouseTracking(False)
        self.statistic_label.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 16px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: light;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.statistic_label.setText("")
        self.statistic_label.setObjectName("statistic_label")
        self.fps_label = QtWidgets.QLabel(self.centralwidget)
        self.fps_label.setGeometry(QtCore.QRect(1140, 50, 100, 40))
        self.fps_label.setMinimumSize(QtCore.QSize(100, 40))
        self.fps_label.setMaximumSize(QtCore.QSize(100, 40))
        self.fps_label.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 20px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(218, 218, 218);\n"
"}\n"
"")
        self.fps_label.setText("")
        self.fps_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fps_label.setObjectName("fps_label")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(1340, 200, 211, 61))
        self.groupBox_5.setStyleSheet("#groupBox_5{\n"
"background-color: rgba(48,148,243,0);\n"
"border: 0px solid #42adff;\n"
"border-left: 0px solid #d9d9d9;\n"
"border-right: 0px solid rgba(29, 83, 185, 255);\n"
"border-radius:0px;}")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.cameraButton = QtWidgets.QPushButton(self.groupBox_5)
        self.cameraButton.setGeometry(QtCore.QRect(80, 20, 65, 28))
        self.cameraButton.setMinimumSize(QtCore.QSize(55, 28))
        self.cameraButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.cameraButton.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(48,148,243,0);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.cameraButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon/摄像头开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cameraButton.setIcon(icon)
        self.cameraButton.setObjectName("cameraButton")
        self.fileButton = QtWidgets.QPushButton(self.groupBox_5)
        self.fileButton.setGeometry(QtCore.QRect(10, 20, 64, 28))
        self.fileButton.setMinimumSize(QtCore.QSize(55, 28))
        self.fileButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.fileButton.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(200, 200, 200,0);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.fileButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icon/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton.setIcon(icon1)
        self.fileButton.setObjectName("fileButton")
        self.rtspButton = QtWidgets.QPushButton(self.groupBox_5)
        self.rtspButton.setEnabled(True)
        self.rtspButton.setGeometry(QtCore.QRect(140, 20, 64, 28))
        self.rtspButton.setMinimumSize(QtCore.QSize(55, 28))
        self.rtspButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.rtspButton.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(48,148,243,0);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.rtspButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icon/实时视频流解析.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rtspButton.setIcon(icon2)
        self.rtspButton.setObjectName("rtspButton")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(360, 690, 40, 40))
        self.runButton.setMinimumSize(QtCore.QSize(40, 40))
        self.runButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);\n"
"}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.runButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/运行.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/暂停.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/运行.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/暂停.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/运行.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/暂停.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/运行.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/暂停.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.runButton.setIcon(icon3)
        self.runButton.setIconSize(QtCore.QSize(30, 30))
        self.runButton.setCheckable(True)
        self.runButton.setObjectName("runButton")
        self.label_91 = QtWidgets.QLabel(self.centralwidget)
        self.label_91.setGeometry(QtCore.QRect(1230, 160, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_91.setFont(font)
        self.label_91.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setIndent(4)
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.centralwidget)
        self.label_92.setGeometry(QtCore.QRect(1230, 210, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_92.setFont(font)
        self.label_92.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setIndent(4)
        self.label_92.setObjectName("label_92")
        self.distance = QtWidgets.QLabel(self.centralwidget)
        self.distance.setGeometry(QtCore.QRect(1410, 660, 131, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.distance.setFont(font)
        self.distance.setStyleSheet("background-color:rgb(78, 157, 236);")
        self.distance.setText("")
        self.distance.setAlignment(QtCore.Qt.AlignCenter)
        self.distance.setObjectName("distance")
        self.iouSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.iouSpinBox_3.setGeometry(QtCore.QRect(1260, 330, 50, 24))
        self.iouSpinBox_3.setMinimumSize(QtCore.QSize(50, 0))
        self.iouSpinBox_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.iouSpinBox_3.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 14px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/img/icon/箭头_列表展开.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/img/icon/箭头_列表展开.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/img/icon/箭头_列表收起.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/img/icon/箭头_列表收起.png);}\n"
"")
        self.iouSpinBox_3.setMaximum(1.0)
        self.iouSpinBox_3.setSingleStep(0.01)
        self.iouSpinBox_3.setProperty("value", 0.45)
        self.iouSpinBox_3.setObjectName("iouSpinBox_3")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1260, 290, 296, 24))
        self.label_15.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"")
        self.label_15.setObjectName("label_15")
        self.iouSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.iouSlider_3.setGeometry(QtCore.QRect(1320, 330, 239, 22))
        self.iouSlider_3.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/img/icon/圆.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.iouSlider_3.setMaximum(100)
        self.iouSlider_3.setProperty("value", 45)
        self.iouSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.iouSlider_3.setObjectName("iouSlider_3")
        self.confSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.confSpinBox_3.setGeometry(QtCore.QRect(1260, 420, 50, 24))
        self.confSpinBox_3.setMinimumSize(QtCore.QSize(50, 0))
        self.confSpinBox_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.confSpinBox_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.confSpinBox_3.setStyleSheet("QDoubleSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 14px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/img/icon/箭头_列表展开.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/img/icon/箭头_列表展开.png);}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/img/icon/箭头_列表收起.png);}\n"
"QDoubleSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/img/icon/箭头_列表收起.png);}\n"
"")
        self.confSpinBox_3.setMaximum(1.0)
        self.confSpinBox_3.setSingleStep(0.01)
        self.confSpinBox_3.setProperty("value", 0.25)
        self.confSpinBox_3.setObjectName("confSpinBox_3")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1260, 380, 296, 24))
        self.label_17.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"")
        self.label_17.setObjectName("label_17")
        self.confSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.confSlider_3.setGeometry(QtCore.QRect(1320, 420, 239, 22))
        self.confSlider_3.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/img/icon/圆.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.confSlider_3.setMaximum(100)
        self.confSlider_3.setProperty("value", 25)
        self.confSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider_3.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.confSlider_3.setObjectName("confSlider_3")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1260, 470, 80, 24))
        self.label_18.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_18.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"")
        self.label_18.setObjectName("label_18")
        self.rateSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.rateSlider_3.setGeometry(QtCore.QRect(1320, 500, 239, 22))
        self.rateSlider_3.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/img/icon/圆.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.rateSlider_3.setMinimum(1)
        self.rateSlider_3.setMaximum(20)
        self.rateSlider_3.setSingleStep(1)
        self.rateSlider_3.setPageStep(1)
        self.rateSlider_3.setProperty("value", 1)
        self.rateSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.rateSlider_3.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.rateSlider_3.setObjectName("rateSlider_3")
        self.rateSpinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.rateSpinBox_3.setGeometry(QtCore.QRect(1260, 500, 50, 24))
        self.rateSpinBox_3.setMinimumSize(QtCore.QSize(50, 0))
        self.rateSpinBox_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.rateSpinBox_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.rateSpinBox_3.setStyleSheet("QSpinBox{\n"
"background:rgba(200, 200, 200,50);\n"
"color:white;\n"
"font-size: 14px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgba(200, 200, 200,100);\n"
"border-radius: 3px;}\n"
"\n"
"QSpinBox::down-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/img/icon/箭头_列表展开.png);}\n"
"QDoubleSpinBox::down-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/img/icon/箭头_列表展开.png);}\n"
"\n"
"QSpinBox::up-button{\n"
"background:rgba(200, 200, 200,0);\n"
"border-image: url(:/img/icon/箭头_列表收起.png);}\n"
"QSpinBox::up-button::hover{\n"
"background:rgba(200, 200, 200,100);\n"
"border-image: url(:/img/icon/箭头_列表收起.png);}\n"
"")
        self.rateSpinBox_3.setMinimum(1)
        self.rateSpinBox_3.setMaximum(20)
        self.rateSpinBox_3.setSingleStep(1)
        self.rateSpinBox_3.setProperty("value", 1)
        self.rateSpinBox_3.setObjectName("rateSpinBox_3")
        self.label_16.raise_()
        self.label_14.raise_()
        self.label.raise_()
        self.label_27.raise_()
        self.label_13.raise_()
        self.label_73.raise_()
        self.stopBn.raise_()
        self.closeLightBn.raise_()
        self.startBn.raise_()
        self.label_4.raise_()
        self.label_74.raise_()
        self.openLightBn.raise_()
        self.label_5.raise_()
        self.clearBn.raise_()
        self.label_75.raise_()
        self.label_76.raise_()
        self.arm_joint1.raise_()
        self.label_77.raise_()
        self.arm_joint2.raise_()
        self.label_78.raise_()
        self.arm_joint3.raise_()
        self.label_79.raise_()
        self.arm_high.raise_()
        self.sendBn.raise_()
        self.label_6.raise_()
        self.label_84.raise_()
        self.label_12.raise_()
        self.label_87.raise_()
        self.label_88.raise_()
        self.label_2.raise_()
        self.label_display.raise_()
        self.label_81.raise_()
        self.label_85.raise_()
        self.speedLb.raise_()
        self.label_86.raise_()
        self.label_83.raise_()
        self.label_82.raise_()
        self.joint3_Lb.raise_()
        self.label_80.raise_()
        self.distanceLb.raise_()
        self.joint2_Lb.raise_()
        self.joint1_Lb.raise_()
        self.directionLb.raise_()
        self.label_89.raise_()
        self.label_90.raise_()
        self.length.raise_()
        self.comboBox.raise_()
        self.statistic_label.raise_()
        self.fps_label.raise_()
        self.groupBox_5.raise_()
        self.runButton.raise_()
        self.label_91.raise_()
        self.label_92.raise_()
        self.distance.raise_()
        self.iouSpinBox_3.raise_()
        self.label_15.raise_()
        self.iouSlider_3.raise_()
        self.confSpinBox_3.raise_()
        self.label_17.raise_()
        self.confSlider_3.raise_()
        self.label_18.raise_()
        self.rateSlider_3.raise_()
        self.rateSpinBox_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_73.setText(_translate("MainWindow", "桥 梁 病 害 检 测 远 程 监 控 平 台"))
        self.stopBn.setText(_translate("MainWindow", "停止"))
        self.closeLightBn.setText(_translate("MainWindow", "关灯"))
        self.startBn.setText(_translate("MainWindow", "启动"))
        self.label_74.setText(_translate("MainWindow", "机器人运动控制"))
        self.openLightBn.setText(_translate("MainWindow", "开灯"))
        self.clearBn.setText(_translate("MainWindow", "清空"))
        self.label_75.setText(_translate("MainWindow", "机械臂运动控制"))
        self.label_76.setText(_translate("MainWindow", "关节1"))
        self.label_77.setText(_translate("MainWindow", "关节2"))
        self.label_78.setText(_translate("MainWindow", "关节3"))
        self.label_79.setText(_translate("MainWindow", "高度"))
        self.sendBn.setText(_translate("MainWindow", "发送"))
        self.label_84.setText(_translate("MainWindow", "实时数据"))
        self.label_88.setText(_translate("MainWindow", "病害检测"))
        self.label_89.setText(_translate("MainWindow", "测距模块/cm"))
        self.label_90.setText(_translate("MainWindow", "裂缝长度/cm"))
        self.label_81.setText(_translate("MainWindow", "测距模块"))
        self.label_85.setText(_translate("MainWindow", "关节3"))
        self.label_86.setText(_translate("MainWindow", "关节2"))
        self.label_83.setText(_translate("MainWindow", "关节1"))
        self.label_82.setText(_translate("MainWindow", "运动方向"))
        self.label_80.setText(_translate("MainWindow", "运动速度"))
        self.cameraButton.setToolTip(_translate("MainWindow", "相机"))
        self.fileButton.setToolTip(_translate("MainWindow", "文件"))
        self.rtspButton.setToolTip(_translate("MainWindow", "rtsp"))
        self.label_91.setText(_translate("MainWindow", "模型选择"))
        self.label_92.setText(_translate("MainWindow", "输入选择"))
        self.label_15.setText(_translate("MainWindow", "IoU"))
        self.label_17.setText(_translate("MainWindow", "置信度"))
        self.label_18.setText(_translate("MainWindow", "帧间延时"))
import apprcc_rc
